environment:
  matrix:
    # node.js
    - nodejs_version: "12"
    - nodejs_version: "10"
    - nodejs_version: "8"

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) x64
  - npm i